# Generated by Django 5.1.5 on 2025-02-17 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='created_at',
            new_name='date_posted',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='author',
            new_name='user',
        ),
        migrations.AddField(
            model_name='article',
            name='is_premium',
            field=models.BooleanField(default=False, verbose_name='is premium article'),
        ),
    ]
